### PR TITLE
New functions/methods + some fixes 

### PR DESCRIPTION
**Pull request by lubieowoce**
**Edit**: *now that I look at it, this is a huge PR... if you'd like me to break it up into smaller ones, please let me know.*

### Fixes:
- Fixed swapped parameters to Vec4 in multiple places (`1cf1e86`)
- Fixed a division by 0 crash in `integrations/glfw` (`173d8bb`)

### Additions:

Drawlists:
```
DrawList:
    add_line
    add_rect
    channels_split
    channels_merge
    channels_set_current

get_overlay_draw_list
```
Styling:
```
get_style

GuiStyle:
    from_ref
    color
```
Cursor functions:
```
get_cursor_pos
set_cursor_pos
set_cursor_screen_pos
```
Mouse functions:
```
is_mouse_down
is_mouse_clicked
is_mouse_released
get_mouse_pos
```
Misc:
```
plot_lines
get_time
```

In addition, I added some aliases. ImGui always shortens "position" to "pos", but we have both `get_window_position()` and `get_cursor_pos()`. It would be nice to settle on one and use it consistently. In the meantime, I added aliases from `*_pos` to `*_position`. (`998d03e`, `b5b165a`)

### CODE REVIEW

**Comment by swistakm** [comment]
Yes it fails on python 2.7 but it's completely unrelated. It's old issue and I'm fixing it right now.

**Comment by swistakm** [comment]
I have added fix for Python 2.7 builds so this should be resolved now. It would be nice to rebase this PR.

Good point with this pos/position inconsistency. I would prefer to have "position" as default name for these Python bindings. Maybe it would be nice to have "pos" aliases marked somehow with warning that this is an alias but it isn't that critical.

There is still ongoing problem with builds on Windows. They are hanging in queued state without any reason. I have submitted issue to Appveyor but if we won't get any fix we may try to use Windows builds on Travis as they are now available. That would greatly simplify the build pipeline.

**Comment by lubieowoce** [comment]
That's great, I prefer "position" too :) I rebased the branch, not sure how to make CI run again.

**Comment by swistakm** [comment]
We don’t have any explicit tests yet but we have some usage examples in docstrings that are used to generate visual examples in the dosctrings. So there is a small pytest plugin that uses autodoc feature of Sphinx to generate tests out of these examples. That’s how we measure coverage. It’s rather doc-coverage than real test-coverage.

I know that’s kinda kludgy but it works. I was even thinking about making some reference images so we could compare these “tests results” with some reference images but I didn’t researched yet how we could do off-screen rendering on Travis/Appveyor.

**Comment by swistakm** [comment]
I’m merging it. There are still some issues on Appveyor builds but these should be now fine as I have merged some CI fixes just recently.

**Comment by lubieowoce** [comment]
> how we could do off-screen rendering on Travis/Appveyor

AFAIK OpenGL doesn't care if there's an actual screen – you just draw to a buffer. So we could just copy its contents and save that! It'd require a bit of work (getting a GLContext without a window?), but it should be possible.

**Comment by lubieowoce** [comment]
This [Stackoverflow answer](https://stackoverflow.com/a/43194644/5534735) talks about testing a GUI app on Travis.

The linked repo's [`travis.yml`](https://github.com/qPCR4vir/nana-demo/blob/master/.travis.yml) sets up a virtual screen with a `DISPLAY` env var. It also references this link: [Travis CI: GUI and headless browsers](https://docs.travis-ci.com/user/gui-and-headless-browsers/) which sounds relevant.

**Comment by swistakm** [comment]
Released as `1.0.0`

**Pull request merged**
