### PR TITLE
Implement several missing functions

### PR DESCRIPTION
**Pull request by potocpav**
I needed those 9 functions for my project. I tried my best to implement them in a way similar to the surrounding code.

### CODE REVIEW

**Comment by swistakm** [comment]
Thanks! This is great PR. I also appreciate all the minor docfixes.

**Comment by potocpav** [comment]
Was the blocker the decreased coverage? If so, how do I increase it - what does it measure?

**Comment by swistakm** [comment]
>Was the blocker the decreased coverage? If so, how do I increase it - what does it measure?

@potocpav: yes, to some extent.

I wanted to add some examples in the docstrings using the :visual-exampe: directive before merging but didn't find enough time to do so. These are executed during tests (so usually bump the coverage) and also included in Sphinx documentation on the readthedocs site. If you include them and all tests pass I will be able to merge it straight away.

Sorry for forgetting about this MR. I'm almost always busy :(

**Comment by potocpav** [comment]
Messed up my repo, accidentally pushed stuff there. Closing.

**Pull request closed without merging**
