### PR TITLE
Support imgui v1.61

### PR DESCRIPTION
**Pull request by tim-rex**
Further to the previous pull request for v1.60
This builds on that with support for v1.61

This pull request is much more complete than 1.60 (and includes all the changes that should have been included in v1.60)
Much greater care has been taken to ensure all relevant changes since v1.51 are incorporated (outside of new functionality).

Note that this branch intentionally excludes any obsolete/deprecated functionality.

The only outstanding item (AFAIK) is to update __init__.py with redeclarations to support autodoc.

### CODE REVIEW

**Comment by swistakm** [comment]
Wow, that's huge and impressive. I will start reviewing it now and tell when I'm done. It may take some time because this PR is very long.

Removing obsolete/deprecated functionalities is fine for me. We will make it as 1.0.0 release and leave notes about introduced backward-incompatibilty. This is what I've have already planned to do when @pconerly started his work on 1.51 update in #61. 

I think that we can close the #72 and focus on this one.

**Comment by pconerly** [comment]
This is awesome! If that means that #61 should just get closed, that's fine.

It'd be great if we could document the missing functionality though, and carve those out as tickets that people can pick up.

**Comment by tim-rex** [comment]
Thanks guys. I got restless and added a few more visual-doc examples - that should bring the coverage checks back up.

I've also added the remaining enum redeclaractions.

I'll leave this pull request as it for now for a proper review, but any/all feedback is welcome. I hope I'm not stepping on any toes here.  This is my first set of pull requests, so.. proper etiquette and all that.

**Comment by swistakm** [comment]
Sorry it took me that much time. I had a pretty intense week.

This is great and you're not stepping on any toes here. I'm pretty sure that everyone will appreciate your tremendous work here.

There are few places where docstrings could be reformatted but I will do it by myself. I'm merging it. This is huge change so I was thinking about doing at least one pre-release version before the official 1.0.0. What do you think about that?

**Comment by tim-rex** [comment]
Pre-release sound like a good idea, definitely.

Actually I started building out a python implementation of ShowDemoWindow()
but quickly encountered the "inout" problems discussed in issue #8

While not relevant for this pull request, is it worth considering issue #8
before a 1.0 release?

**Comment by swistakm** [comment]
@tim-rex Yes, it is already assigned to 1.0.0 milestone.

**Comment by swistakm** [comment]
Released as `1.0.0`

**Pull request merged**
