### PR TITLE
Adding new examples

### PR DESCRIPTION
**Pull request by LuminousLizard**
(1) Python/Pyimgui rewrite of the imgui demo window (WIP)
(2) 2 example scripts to demonstrate possible mistakes and program structures
All 3 scripts currently for the pygame backend.

### CODE REVIEW

**Comment by cellularmitosis** [comment]
@LuminousLizard thanks for posting this!  hopefully it will get merged.

**Comment by swistakm** [comment]
@LuminousLizard thanks for the MR. The more examples the better! I have finally some free time so will start pulling all these MRs from my personal "backlog".

**Comment by LuminousLizard** [comment]
@cellularmitosis ... thanks for reminding me to keep working xD ... the demo window is still WIP, but now I'm back

@swistakm I will complete the demo window and add a version for everyone backend. Maybe I can think of some more useful examples.

**Comment by Red-Pheonix** [comment]
Running pygame_demo_window_impl doesn't work in my case.I had to make some changes to make it work. 

1. move imgui.create_context() before imgui.get_io()
2. add renderer.render(imgui.get_draw_data()) before pygame.display.flip()

**Comment by LuminousLizard** [comment]
> Running pygame_demo_window_impl doesn't work in my case.I had to make some changes to make it work.
> 
>     1. move imgui.create_context() before imgui.get_io()
> 
>     2. add renderer.render(imgui.get_draw_data()) before pygame.display.flip()

Right because the examples are from the time of version 0.1.0. I have not taken the time to update the examples.

**Pull request merged**
