### PR TITLE
Add several drawing functions with documentation and examples

### PR DESCRIPTION
**Pull request by potocpav**
This PR adds several functions from the raw drawing API: `AddCircle`, `AddCircleFilled`, `AddText`, `AddImage`, and `AddPolyline`. All of these are members of `_DrawList`, which I added to documentation.

Each of the newly-implemented functions have visual examples, and I tried my best to document them similarly to other functions in PyImGui. I didn't know if I should include the visual examples themselves, so I did.

This PR is a continuation of #103, but I added visual examples and limited the focus on `_DrawList` functions. It partly intersects with #123, but with (hopefully) better documentation. It also (partly?) solves #49.

### CODE REVIEW

**Comment by potocpav** [comment]
The deletions in imgui/core.pyx are just because I reordered the drawing functions to match the order in imgui

**Comment by swistakm** [comment]
This is rad! Thank you for the contribution.

Sorry it took me so long to review.

**Comment by potocpav** [comment]
Great that it got merged! Together with the other recent updates, this will enable me to throw away my fork and publish a project on pypi. Thanks :)

**Comment by swistakm** [comment]
Great to hear that. As soon as the build completes I will publish new version.

**Comment by swistakm** [comment]
This has been released in [1.1.0](https://github.com/swistakm/pyimgui/releases/tag/1.1.0) and is available for download from PyPI.

**Pull request merged**
