### PR TITLE
Support scope id stack handling for widgets with the same name

### LINKED ISSUE #56: How to handle multiple widgets with same "implicit" ID
This isn't actually a bug but it may look like one.

Some widgets get same "implicit" id and usually this is the value of widget's label parameter. For instance:

```
if imgui.button("OK"):
    print("OK1")
if imgui.button("OK"):
    print("OK2")
```
All above buttons will have same label `"OK"`. Both buttons will look like clickable but only the first one will trigger on clicking. This would be a problem for common labels like yes/no/OK/cancel etc. but these usually are on different windows and windows have different IDs scopes. e.g. if we use following code:

```
imgui.begin("Win1")
if imgui.button("OK"):
    print("W1-OK1")
if imgui.button("OK"):
    print("W1-OK2")
imgui.end()

imgui.begin("Win1")
if imgui.button("OK"):
    print("W2-OK1")
if imgui.button("OK"):
    print("W2-OK2")
imgui.end()
```
We will see `W1-OK1` and `W2-OK1` in output but no `W1-OK2` nor `W2-OK2`. ImGui exposes following functions to maintain such ID scopes:
```
    void PushID(const char* str_id)
    void PushID(const char* str_id_begin, const char* str_id_end)
    void PushID(const void* ptr_id)
    void PushID(int int_id)
    void PopID()
```

In order to solve such problems they need to be ported. We already have additional context managers for managing push/pop actions on fonts and styles so we could also create custom `scope` or `scoped` context manager that would make code more readable. We would then have two ways to interact with scopes:

```
if imgui.button("OK"):
    print("OK outside scope")

imgui.push_id("my scope")
if imgui.button("OK"):
    print("OK in scope")
imgui.pop_id()

# or ...

if imgui.button("OK"):
    print("OK outside scope")

with imgui.scope("my scope"):
    if imgui.button("OK"):
        print("OK in scope")
```

### PR DESCRIPTION
**Pull request by 602p**
This adds functions to expose the PushID and PopID capability in imgui for manipulating the widget id stack. This allows you to elegantly have multiple widgets with the same implicit ids (usually their name.)

It also adds a simple context manager to the `extra` module that automates the pushing and popping of scope ids, and allows use without manually specifying an object to be the scope id (by creating an anonymous object for this purpose.)

Not sure what the conclusion was on #33 , but I placed the context manager in the extra module per [discussion](https://github.com/swistakm/pyimgui/issues/56#issuecomment-381397461).

This closes #56 , assuming it is to @swistakm 's liking.

### CODE REVIEW

**Comment by 602p** [comment]
I've removed the behavior of the context manager where it would create an arbitrary object to be the scope. After running my project against the patch it seems like that dosen't work for all cases. It appears to be important that the scope object is the same between frames for things that have state managed by imgui (e.g. collapsed state of a treenode.) That is, if you have multiple `imgui.tree_node`s with the same name, they all open/close together. If you give them all different scopes but use the same scope object each frame, it works perfectly. If you give them different scopes but change the scopes every frame then they will not respond to clicks at all (because imgui can't keep track of which is which with the different scopes.)

To go with this, I've changed it so that when you call `push_id` with an integer it pushes the value (as opposed to the address,) and when used with a string it similarly uses the imgui variant that will internally check string equality. This should make it behave as expected across frames for people using integers or strings as contexts.

It's up for debate as far as what we want to offer in the context manager. Since creating an new object for the scope each frame only does what you want some of the time, it seems dangerous to have (at least as a default.) Therefore I removed that and it's almost exactly what was suggested in the issue. Maybe we want some utility class that is a context manager that pushes itself as the scope, thereby allowing you to keep a reference to it across frames?

Here is a quick recipe for that:
```python
class Scope:
    def __enter__(self):
        imgui.push_id(self)

    def __exit__(self, *args):
        imgui.pop_id()

#used like

s=Scope()
with s:
    imgui.button('abc')
```

I'm not sure if that's useful enough to merit inclusion in extra (at least, I don't think I'd find myself using that over using the piece of data I am constructing the UI for as my scope.)

**Comment by swistakm** [comment]
Your observations about scopes are very good so it nice you have captured them in the docs. I will just have to take closer look at this case with int but generally the PR looks very nice. Also I have few comments related to docs and style so if you have spare time you can fix them in the meantime.

About the mentioned `Scope()` utility from the extra recipe. I think we can live without that. It is also risky because less experienced developers may use it wrongly (create at every frame as you have already mentioned) and this will be very confusing.  

Thanks for contribution!

**Comment by traverseda** [comment]
Any progress on this? I'd fine it useful.

**Comment by swistakm** [comment]
I will take another look at this MR next week

**Comment by gingerBill** [comment]
Will this be added soon to the latest release?

**Comment by swistakm** [comment]
I'm closing this because alternative implementation has been already merged.

**Comment by swistakm** [comment]
Feature released in 1.2.0

**Pull request closed without merging**
