### PR TITLE
Add support for ImGuiIO clipboard callbacks

### PR DESCRIPTION
**Pull request by scotty007**
Allows user/system clipboard integration (aside from the internal ImGui clipboard and the out-of-the-box supported Windows clipboard).
System clipboard is enabled in GLFW integration.

### CODE REVIEW

**Comment by swistakm** [comment]
Thanks for contribution! It features callbacks and we had some memory-safety issues when doing callbacks in different place. So I will just do some testing manually to check whether this needs some warnings in documentation. Will try to do that as soon as possible

**Comment by scotty007** [comment]
@swistakm Thanks for developing and maintaining this awesome library!

There may also be Python 2/3 type compatibility issues when passing strings around. I can't trigger TypeErrors with the clipboard callbacks, but I stumbled upon such errors when I tried to add support for `GetClipboardText()` and `SetClipboardText()`. When I get this solved I can add docstring examples for unit testing (w/o this two functions a would have to fake user input somehow, is this possible?).

BTW: These type errors are triggered in `imgui.core.show_style_selector()` as well (Python 3). I will open an issue after further investigation.

**Comment by swistakm** [comment]
Thanks for PR, sorry it took so long to review. I have verified the SDL2 implementation under Python2 and Python3 and fixed the typing issue I think you was referring to.

**Comment by swistakm** [comment]
Feature released in 1.2.0.

**Comment by scotty007** [comment]
Thanks for the release! Installed it already :-)

**Pull request merged**
