### PR TITLE
Enable setup.py to install cython if it isn't already.

### PR DESCRIPTION
**Pull request by stuaxo**
Make  ```python setup.py develop``` or ```python setup.py install``` install cython if it is not already.

Add install_requires with cython, (and make import completely optional).

### CODE REVIEW

**Comment by stuaxo** [comment]
@swistakm I'm not really sure what the error in appveyor is about, doesn't seem to be introduced by the patch though.

**Comment by swistakm** [comment]
Oh, yeah. This issue happens from time to time on AppVeyor and is caused by `git-lfs`. I've hit "rebuild" button.

**Comment by swistakm** [comment]
Once build passed we can start the discussion.

I did not add `Cython` to the package requirements rather on purpose. I primarily wanted to distribute both Cython `.pyx` and C++ `.cpp` sources as *sdist package*  and leave the decision whether to use Cython or plain C++ compilation to the final user. This is actually a solution suggested by [Cython documentation](http://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules).

My general idea is to include both Cython and C++ sources in sdist package and trigger Cython installation using setuptools' `extras_require` option, e.g.:

    pip install imgui[Cython]

Question is: should Cython existence (determined with `try ... import` block) be enough to trigger actual Cython compilation instead of plain C++ compilation? I think we should be fine with this. What do you think @stuaxo? We can always add additional environment variable later to enable/disable such behaviour.

Still, I will merge this PR because we will have to use this `cythonize()` function stub anyway but I will remove the `install_requires` and `setup_requires` soon.

**Comment by stuaxo** [comment]
That all sounds really sensible.   We should be fine with the try... import + optional environment variable.

**Pull request merged**
